/**
 * One-shot self-hosting of the site's web fonts.
 *
 * Previously the site loaded Geist + Geist Mono (and an unused Inter) from
 * fonts.googleapis.com via a render-blocking <link>. This downloads the
 * latin-subset WOFF2 files for the weights we actually use, writes them to
 * public/fonts/, and emits a self-contained @font-face stylesheet
 * (src/styles/fonts.css) so there are zero third-party font requests at runtime.
 *
 * Reproducible: run `node scripts/fetch-fonts.mjs`. The committed woff2 + css
 * are what the build consumes, so production does not depend on this script or
 * on network access.
 */
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const fontsDir = path.join(root, "public", "fonts");
const cssOut = path.join(root, "src", "styles", "fonts.css");

// Families + weights the design actually uses (Inter dropped — it was only ever
// a fallback in the stack and was never the rendered face).
const FAMILIES = [
  { css: "Geist", file: "geist", weights: [300, 400, 500, 600, 700] },
  { css: "Geist Mono", file: "geist-mono", weights: [400, 500, 600] },
  // IBM Plex Mono is IBM's official OFL-licensed font, served by Google Fonts.
  // Self-hosted (the real font, not a substitute) for mono labels/nav/metrics.
  { css: "IBM Plex Mono", file: "ibm-plex-mono", weights: [400, 500, 600] },
];

const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36";

await mkdir(fontsDir, { recursive: true });
await mkdir(path.dirname(cssOut), { recursive: true });

const faceBlocks = [];

for (const fam of FAMILIES) {
  const familyParam = fam.css.replace(/ /g, "+");
  const url = `https://fonts.googleapis.com/css2?family=${familyParam}:wght@${fam.weights.join(";")}&display=swap`;
  const css = await fetch(url, { headers: { "User-Agent": UA } }).then((r) => r.text());

  // Split into @font-face blocks and keep only the basic-latin subset
  // (the block whose unicode-range starts at U+0000-00FF).
  const blocks = css.split("@font-face").slice(1);
  for (const block of blocks) {
    if (!/unicode-range:\s*U\+0000-00FF/.test(block)) continue;
    const weight = (block.match(/font-weight:\s*(\d+)/) || [])[1];
    const src = (block.match(/src:\s*url\(([^)]+)\)/) || [])[1];
    if (!weight || !src) continue;

    const outName = `${fam.file}-${weight}.woff2`;
    const buf = Buffer.from(await fetch(src, { headers: { "User-Agent": UA } }).then((r) => r.arrayBuffer()));
    await writeFile(path.join(fontsDir, outName), buf);
    console.log(`[font] ${fam.css} ${weight} -> fonts/${outName}  ${(buf.length / 1024).toFixed(1)} KB`);

    faceBlocks.push(
      `@font-face {\n` +
        `  font-family: "${fam.css}";\n` +
        `  font-style: normal;\n` +
        `  font-weight: ${weight};\n` +
        `  font-display: swap;\n` +
        `  src: url("/fonts/${outName}") format("woff2");\n` +
        `}`,
    );
  }
}

const header =
  "/* Self-hosted fonts. Generated by scripts/fetch-fonts.mjs — do not edit by hand.\n" +
  "   Latin subset, WOFF2, font-display: swap. */\n\n";
await writeFile(cssOut, header + faceBlocks.join("\n\n") + "\n");
console.log(`[font] wrote ${faceBlocks.length} @font-face rules -> ${path.relative(root, cssOut)}`);
